local function get_full_path(assetname)
  return "./mods/ews/assets/" .. assetname
end

EWS_Log("Registering assets")

DB:create_entry("xml", "core/settings/editor_types", get_full_path("editor_types.xml"))
DB:create_entry("xml", "lib/utils/dev/editor/xml/predefined_instances", get_full_path("predefined_instances.xml"))
DB:create_entry("xml", "lib/utils/dev/editor/xml/predefined_worlds", get_full_path("predefined_worlds.xml"))

DB:create_entry("controller", "core/lib/utils/dev/editor/xml/default_controller", get_full_path("default_controller.xml")) -- from Lead and Gold

--required editor units 
DB:create_entry("cooked_physics", "core/units/dome_occ_shape/dome_occ_shape", get_full_path("core/units/dome_occ_shape/dome_occ_shape.cooked_physics"))
DB:create_entry("model", "core/units/dome_occ_shape/dome_occ_shape", get_full_path("core/units/dome_occ_shape/dome_occ_shape.model"))
DB:create_entry("object", "core/units/dome_occ_shape/dome_occ_shape",  get_full_path("core/units/dome_occ_shape/dome_occ_shape.object"))
DB:create_entry("unit", "core/units/dome_occ_shape/dome_occ_shape",  get_full_path("core/units/dome_occ_shape/dome_occ_shape.unit"))
DB:create_entry("cooked_physics", "core/units/effect/effect", get_full_path("core/units/effect/effect.cooked_physics"))
DB:create_entry("model", "core/units/effect/effect", get_full_path("core/units/effect/effect.model"))
DB:create_entry("object", "core/units/effect/effect", get_full_path("core/units/effect/effect.object"))
DB:create_entry("unit", "core/units/effect/effect", get_full_path("core/units/effect/effect.unit"))
DB:create_entry("cooked_physics", "core/units/effect/effect", get_full_path("core/units/effect/effect.cooked_physics"))
DB:create_entry("model", "core/units/environment_area/environment_area", get_full_path("core/units/environment_area/environment_area.model"))
DB:create_entry("object", "core/units/environment_area/environment_area", get_full_path("core/units/environment_area/environment_area.object"))
DB:create_entry("unit", "core/units/environment_area/environment_area", get_full_path("core/units/environment_area/environment_area.unit"))
DB:create_entry("cooked_physics", "core/units/patrol_point/patrol_point", get_full_path("core/units/patrol_point/patrol_point.cooked_physics"))
DB:create_entry("model", "core/units/patrol_point/patrol_point", get_full_path("core/units/patrol_point/patrol_point.model"))
DB:create_entry("object", "core/units/patrol_point/patrol_point", get_full_path("core/units/patrol_point/patrol_point.object"))
DB:create_entry("unit", "core/units/patrol_point/patrol_point", get_full_path("core/units/patrol_point/patrol_point.unit"))
DB:create_entry("cooked_physics", "core/units/portal_shape/portal_shape", get_full_path("core/units/portal_shape/portal_shape.cooked_physics"))
DB:create_entry("model", "core/units/portal_shape/portal_shape", get_full_path("core/units/portal_shape/portal_shape.model"))
DB:create_entry("object", "core/units/portal_shape/portal_shape", get_full_path("core/units/portal_shape/portal_shape.object"))
DB:create_entry("unit", "core/units/portal_shape/portal_shape", get_full_path("core/units/portal_shape/portal_shape.unit"))
DB:create_entry("cooked_physics", "core/units/sound_area_emitter/sound_area_emitter", get_full_path("core/units/sound_area_emitter/sound_area_emitter.cooked_physics"))
DB:create_entry("model", "core/units/sound_area_emitter/sound_area_emitter", get_full_path("core/units/sound_area_emitter/sound_area_emitter.model"))
DB:create_entry("object", "core/units/sound_area_emitter/sound_area_emitter", get_full_path("core/units/sound_area_emitter/sound_area_emitter.object"))
DB:create_entry("unit", "core/units/sound_area_emitter/sound_area_emitter", get_full_path("core/units/sound_area_emitter/sound_area_emitter.unit"))
DB:create_entry("cooked_physics", "core/units/sound_emitter/sound_emitter", get_full_path("core/units/sound_emitter/sound_emitter.cooked_physics"))
DB:create_entry("model", "core/units/sound_emitter/sound_emitter", get_full_path("core/units/sound_emitter/sound_emitter.model"))
DB:create_entry("object", "core/units/sound_emitter/sound_emitter", get_full_path("core/units/sound_emitter/sound_emitter.object"))
DB:create_entry("unit", "core/units/sound_emitter/sound_emitter", get_full_path("core/units/sound_emitter/sound_emitter.unit"))
DB:create_entry("cooked_physics", "core/units/sound_environment/sound_environment", get_full_path("core/units/portal_shape/portal_shape.cooked_physics"))
DB:create_entry("model", "core/units/sound_environment/sound_environment", get_full_path("core/units/sound_environment/sound_environment.model"))
DB:create_entry("object", "core/units/sound_environment/sound_environment", get_full_path("core/units/sound_environment/sound_environment.object"))
DB:create_entry("unit", "core/units/sound_environment/sound_environment", get_full_path("core/units/sound_environment/sound_environment.unit"))
